/**
 * workspace/agent-workflow-record-db.ts — Stage 112 (+ Stage 112B scoping)
 *
 * D1 persistence for saved intake Agent Workflow Records. A record holds the
 * deterministic workflow snapshot generated by the dashboard intake preview
 * (acceptance map + stage plan + agent run plan + evidence plan). The JSON
 * snapshots are stored as TEXT for D1 compatibility.
 *
 * Stage 112B: every record is scoped to a `user_key` (the workspace key that
 * created it), matching the existing workspace convention. All reads filter by
 * user_key; detail callers must verify ownership before returning a record.
 *
 * This is NOT agent execution. No real evidence, decisions, outcomes, benchmark
 * ids, or evolution action packs are persisted here.
 */
import type { Env } from "../env.js";

export type WorkflowRecordStatus = "draft" | "planned" | "needs_evidence" | "archived";

export const WORKFLOW_RECORD_STATUSES: WorkflowRecordStatus[] = [
  "draft",
  "planned",
  "needs_evidence",
  "archived",
];

/** Full persisted record (snapshots parsed back into objects). */
export type DbWorkflowRecord = {
  id: string;
  projectId: string | null;
  intakeType: string;
  title: string;
  sourceSummary: string;
  rawInputExcerpt: string | null;
  acceptanceMap: unknown;
  stagePlan: unknown;
  agentRunPlan: unknown;
  evidencePlan: unknown;
  status: string;
  createdAt: string;
  updatedAt: string;
};

/** Full record plus its owning user_key (internal — for ownership checks). */
export type OwnedWorkflowRecord = DbWorkflowRecord & { userKey: string };

/** Lightweight list item (no JSON snapshots). */
export type WorkflowRecordListItem = {
  id: string;
  projectId: string | null;
  intakeType: string;
  title: string;
  sourceSummary: string;
  status: string;
  createdAt: string;
  updatedAt: string;
};

type RecordRow = {
  id: string;
  user_key: string;
  project_id: string | null;
  intake_type: string;
  title: string;
  source_summary: string;
  raw_input_excerpt: string | null;
  acceptance_map_json: string;
  stage_plan_json: string;
  agent_run_plan_json: string;
  evidence_plan_json: string;
  status: string;
  created_at: string;
  updated_at: string;
};

function randId(prefix: string): string {
  const ts = Date.now().toString(36).slice(-6);
  const r = Math.random().toString(36).slice(2, 6);
  return `${prefix}_${ts}${r}`;
}

function safeParse(json: string): unknown {
  try {
    return JSON.parse(json);
  } catch {
    return null;
  }
}

export async function insertWorkflowRecord(
  env: Env,
  input: {
    userKey: string;
    projectId?: string | null;
    intakeType: string;
    title: string;
    sourceSummary: string;
    rawInputExcerpt?: string | null;
    acceptanceMapJson: string;
    stagePlanJson: string;
    agentRunPlanJson: string;
    evidencePlanJson: string;
    status: WorkflowRecordStatus;
    now?: string;
  },
): Promise<DbWorkflowRecord> {
  const id = randId("wawr");
  const now = input.now ?? new Date().toISOString();
  const projectId = input.projectId ?? null;
  const rawInputExcerpt = input.rawInputExcerpt ?? null;

  await env.DB.prepare(
    `INSERT INTO workspace_agent_workflow_records
       (id, user_key, project_id, intake_type, title, source_summary, raw_input_excerpt,
        acceptance_map_json, stage_plan_json, agent_run_plan_json, evidence_plan_json,
        status, created_at, updated_at)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
  )
    .bind(
      id,
      input.userKey,
      projectId,
      input.intakeType,
      input.title,
      input.sourceSummary,
      rawInputExcerpt,
      input.acceptanceMapJson,
      input.stagePlanJson,
      input.agentRunPlanJson,
      input.evidencePlanJson,
      input.status,
      now,
      now,
    )
    .run();

  return {
    id,
    projectId,
    intakeType: input.intakeType,
    title: input.title,
    sourceSummary: input.sourceSummary,
    rawInputExcerpt,
    acceptanceMap: safeParse(input.acceptanceMapJson),
    stagePlan: safeParse(input.stagePlanJson),
    agentRunPlan: safeParse(input.agentRunPlanJson),
    evidencePlan: safeParse(input.evidencePlanJson),
    status: input.status,
    createdAt: now,
    updatedAt: now,
  };
}

export async function listWorkflowRecords(
  env: Env,
  opts: { userKey: string; projectId?: string; includeArchived?: boolean; limit?: number },
): Promise<WorkflowRecordListItem[]> {
  const limit = opts.limit && opts.limit > 0 ? Math.min(opts.limit, 100) : 50;
  // Always scoped to the caller's user_key. The optional project_id filter
  // applies WITHIN that scope. Archived records are excluded by default
  // (Stage 118) unless includeArchived is set.
  const where = ["user_key = ?"];
  const binds: Array<string | number> = [opts.userKey];
  if (opts.projectId) {
    where.push("project_id = ?");
    binds.push(opts.projectId);
  }
  if (!opts.includeArchived) {
    where.push("status != 'archived'");
  }
  binds.push(limit);

  const res = await env.DB.prepare(
    `SELECT id, project_id, intake_type, title, source_summary, status, created_at, updated_at
       FROM workspace_agent_workflow_records
      WHERE ${where.join(" AND ")}
      ORDER BY created_at DESC
      LIMIT ?`,
  )
    .bind(...binds)
    .all();
  const rows = (res?.results ?? []) as Array<{
    id: string;
    project_id: string | null;
    intake_type: string;
    title: string;
    source_summary: string;
    status: string;
    created_at: string;
    updated_at: string;
  }>;
  return rows.map((row) => ({
    id: row.id,
    projectId: row.project_id ?? null,
    intakeType: row.intake_type,
    title: row.title,
    sourceSummary: row.source_summary,
    status: row.status,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  }));
}

/**
 * Fetch a record by id INCLUDING its owning user_key. Callers MUST verify
 * `record.userKey === currentUserKey` (returning 404 otherwise) before exposing
 * it — the id alone does not authorize access.
 */
export async function getOwnedWorkflowRecordById(
  env: Env,
  id: string,
): Promise<OwnedWorkflowRecord | null> {
  const row = (await env.DB.prepare(
    `SELECT id, user_key, project_id, intake_type, title, source_summary, raw_input_excerpt,
            acceptance_map_json, stage_plan_json, agent_run_plan_json, evidence_plan_json,
            status, created_at, updated_at
       FROM workspace_agent_workflow_records WHERE id = ?`,
  )
    .bind(id)
    .first()) as RecordRow | null;
  if (!row) return null;
  return {
    userKey: row.user_key,
    id: row.id,
    projectId: row.project_id ?? null,
    intakeType: row.intake_type,
    title: row.title,
    sourceSummary: row.source_summary,
    rawInputExcerpt: row.raw_input_excerpt ?? null,
    acceptanceMap: safeParse(row.acceptance_map_json),
    stagePlan: safeParse(row.stage_plan_json),
    agentRunPlan: safeParse(row.agent_run_plan_json),
    evidencePlan: safeParse(row.evidence_plan_json),
    status: row.status,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

/**
 * Update a record's status (Stage 118 — archive/restore). The caller MUST have
 * already verified ownership (`record.userKey === currentUserKey`); this updates
 * by id only. Returns the new updatedAt.
 */
export async function updateWorkflowRecordStatus(
  env: Env,
  id: string,
  status: WorkflowRecordStatus,
  now?: string,
): Promise<string> {
  const updatedAt = now ?? new Date().toISOString();
  await env.DB.prepare(
    `UPDATE workspace_agent_workflow_records SET status = ?, updated_at = ? WHERE id = ?`,
  )
    .bind(status, updatedAt, id)
    .run();
  return updatedAt;
}

/**
 * Hard-delete a record by id (Stage 118 — explicit removal). The caller MUST
 * have already verified ownership before calling this.
 */
export async function deleteWorkflowRecordById(env: Env, id: string): Promise<void> {
  await env.DB.prepare(`DELETE FROM workspace_agent_workflow_records WHERE id = ?`).bind(id).run();
}

/** Admin list item — includes the owning user_key (operator-only view). */
export type AdminWorkflowRecordListItem = WorkflowRecordListItem & { userKey: string };

export type AdminWorkflowRecordSummary = {
  total: number;
  byStatus: Record<string, number>;
  byIntakeType: Record<string, number>;
  uniqueUserKeys: number;
};

/**
 * Stage 121 — admin/beta-operations list ACROSS userKey scopes. Returns summary
 * fields only (NO snapshot JSON) to limit sensitive exposure. Authorization is
 * the caller's responsibility (admin-key gated at the route). A FETCH_CAP bounds
 * the scan; `summary` is computed over the fetched set and `records` is the first
 * `limit` of it.
 */
export async function adminListWorkflowRecords(
  env: Env,
  opts: { userKey?: string; status?: string; includeArchived?: boolean; limit?: number } = {},
): Promise<{ records: AdminWorkflowRecordListItem[]; summary: AdminWorkflowRecordSummary }> {
  const FETCH_CAP = 1000;
  const limit = opts.limit && opts.limit > 0 ? Math.min(opts.limit, 200) : 50;

  const where: string[] = [];
  const binds: Array<string | number> = [];
  if (opts.userKey) {
    where.push("user_key = ?");
    binds.push(opts.userKey);
  }
  if (opts.status) {
    where.push("status = ?");
    binds.push(opts.status);
  } else if (!opts.includeArchived) {
    where.push("status != 'archived'");
  }
  binds.push(FETCH_CAP);

  const res = await env.DB.prepare(
    `SELECT id, user_key, project_id, intake_type, title, source_summary, status, created_at, updated_at
       FROM workspace_agent_workflow_records
      ${where.length ? `WHERE ${where.join(" AND ")}` : ""}
      ORDER BY created_at DESC
      LIMIT ?`,
  )
    .bind(...binds)
    .all();

  const rows = (res?.results ?? []) as Array<{
    id: string;
    user_key: string;
    project_id: string | null;
    intake_type: string;
    title: string;
    source_summary: string;
    status: string;
    created_at: string;
    updated_at: string;
  }>;

  const byStatus: Record<string, number> = {};
  const byIntakeType: Record<string, number> = {};
  const userKeys = new Set<string>();
  for (const r of rows) {
    byStatus[r.status] = (byStatus[r.status] ?? 0) + 1;
    byIntakeType[r.intake_type] = (byIntakeType[r.intake_type] ?? 0) + 1;
    userKeys.add(r.user_key);
  }

  const records = rows.slice(0, limit).map((r) => ({
    id: r.id,
    userKey: r.user_key,
    projectId: r.project_id ?? null,
    intakeType: r.intake_type,
    title: r.title,
    sourceSummary: r.source_summary,
    status: r.status,
    createdAt: r.created_at,
    updatedAt: r.updated_at,
  }));

  return {
    records,
    summary: {
      total: rows.length,
      byStatus,
      byIntakeType,
      uniqueUserKeys: userKeys.size,
    },
  };
}
