/**
 * workspace/agent-workflow-record-db.ts — Stage 112
 *
 * D1 persistence for saved intake Agent Workflow Records. A record holds the
 * deterministic workflow snapshot generated by the dashboard intake preview
 * (acceptance map + stage plan + agent run plan + evidence plan). The JSON
 * snapshots are stored as TEXT for D1 compatibility.
 *
 * This is NOT agent execution. No real evidence, decisions, outcomes, benchmark
 * ids, or evolution action packs are persisted here.
 */
import type { Env } from "../env.js";

export type WorkflowRecordStatus = "draft" | "planned" | "needs_evidence" | "archived";

export const WORKFLOW_RECORD_STATUSES: WorkflowRecordStatus[] = [
  "draft",
  "planned",
  "needs_evidence",
  "archived",
];

/** Full persisted record (snapshots parsed back into objects). */
export type DbWorkflowRecord = {
  id: string;
  projectId: string | null;
  intakeType: string;
  title: string;
  sourceSummary: string;
  rawInputExcerpt: string | null;
  acceptanceMap: unknown;
  stagePlan: unknown;
  agentRunPlan: unknown;
  evidencePlan: unknown;
  status: string;
  createdAt: string;
  updatedAt: string;
};

/** Lightweight list item (no JSON snapshots). */
export type WorkflowRecordListItem = {
  id: string;
  projectId: string | null;
  intakeType: string;
  title: string;
  sourceSummary: string;
  status: string;
  createdAt: string;
  updatedAt: string;
};

type RecordRow = {
  id: string;
  project_id: string | null;
  intake_type: string;
  title: string;
  source_summary: string;
  raw_input_excerpt: string | null;
  acceptance_map_json: string;
  stage_plan_json: string;
  agent_run_plan_json: string;
  evidence_plan_json: string;
  status: string;
  created_at: string;
  updated_at: string;
};

function randId(prefix: string): string {
  const ts = Date.now().toString(36).slice(-6);
  const r = Math.random().toString(36).slice(2, 6);
  return `${prefix}_${ts}${r}`;
}

function safeParse(json: string): unknown {
  try {
    return JSON.parse(json);
  } catch {
    return null;
  }
}

export async function insertWorkflowRecord(
  env: Env,
  input: {
    projectId?: string | null;
    intakeType: string;
    title: string;
    sourceSummary: string;
    rawInputExcerpt?: string | null;
    acceptanceMapJson: string;
    stagePlanJson: string;
    agentRunPlanJson: string;
    evidencePlanJson: string;
    status: WorkflowRecordStatus;
    now?: string;
  },
): Promise<DbWorkflowRecord> {
  const id = randId("wawr");
  const now = input.now ?? new Date().toISOString();
  const projectId = input.projectId ?? null;
  const rawInputExcerpt = input.rawInputExcerpt ?? null;

  await env.DB.prepare(
    `INSERT INTO workspace_agent_workflow_records
       (id, project_id, intake_type, title, source_summary, raw_input_excerpt,
        acceptance_map_json, stage_plan_json, agent_run_plan_json, evidence_plan_json,
        status, created_at, updated_at)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
  )
    .bind(
      id,
      projectId,
      input.intakeType,
      input.title,
      input.sourceSummary,
      rawInputExcerpt,
      input.acceptanceMapJson,
      input.stagePlanJson,
      input.agentRunPlanJson,
      input.evidencePlanJson,
      input.status,
      now,
      now,
    )
    .run();

  return {
    id,
    projectId,
    intakeType: input.intakeType,
    title: input.title,
    sourceSummary: input.sourceSummary,
    rawInputExcerpt,
    acceptanceMap: safeParse(input.acceptanceMapJson),
    stagePlan: safeParse(input.stagePlanJson),
    agentRunPlan: safeParse(input.agentRunPlanJson),
    evidencePlan: safeParse(input.evidencePlanJson),
    status: input.status,
    createdAt: now,
    updatedAt: now,
  };
}

export async function listWorkflowRecords(
  env: Env,
  opts: { projectId?: string; limit?: number } = {},
): Promise<WorkflowRecordListItem[]> {
  const limit = opts.limit && opts.limit > 0 ? Math.min(opts.limit, 100) : 50;
  // project_id filter is optional — records may exist without a project.
  const stmt = opts.projectId
    ? env.DB.prepare(
        `SELECT id, project_id, intake_type, title, source_summary, status, created_at, updated_at
           FROM workspace_agent_workflow_records
          WHERE project_id = ?
          ORDER BY created_at DESC
          LIMIT ?`,
      ).bind(opts.projectId, limit)
    : env.DB.prepare(
        `SELECT id, project_id, intake_type, title, source_summary, status, created_at, updated_at
           FROM workspace_agent_workflow_records
          ORDER BY created_at DESC
          LIMIT ?`,
      ).bind(limit);

  const res = await stmt.all();
  const rows = (res?.results ?? []) as Array<{
    id: string;
    project_id: string | null;
    intake_type: string;
    title: string;
    source_summary: string;
    status: string;
    created_at: string;
    updated_at: string;
  }>;
  return rows.map((row) => ({
    id: row.id,
    projectId: row.project_id ?? null,
    intakeType: row.intake_type,
    title: row.title,
    sourceSummary: row.source_summary,
    status: row.status,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  }));
}

export async function getWorkflowRecordById(env: Env, id: string): Promise<DbWorkflowRecord | null> {
  const row = (await env.DB.prepare(
    `SELECT id, project_id, intake_type, title, source_summary, raw_input_excerpt,
            acceptance_map_json, stage_plan_json, agent_run_plan_json, evidence_plan_json,
            status, created_at, updated_at
       FROM workspace_agent_workflow_records WHERE id = ?`,
  )
    .bind(id)
    .first()) as RecordRow | null;
  if (!row) return null;
  return {
    id: row.id,
    projectId: row.project_id ?? null,
    intakeType: row.intake_type,
    title: row.title,
    sourceSummary: row.source_summary,
    rawInputExcerpt: row.raw_input_excerpt ?? null,
    acceptanceMap: safeParse(row.acceptance_map_json),
    stagePlan: safeParse(row.stage_plan_json),
    agentRunPlan: safeParse(row.agent_run_plan_json),
    evidencePlan: safeParse(row.evidence_plan_json),
    status: row.status,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}
